In [63]:
#vaccinations by date for countries
import pandas as pd
import json
base="https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/internal/megafile--vaccinations.json"

df = pd.read_json(base)

df

,location,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,new_vaccinations_smoothed_per_million,population
0,Afghanistan,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,38928341.0
1,Afghanistan,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,38928341.0
2,Afghanistan,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,38928341.0
3,Afghanistan,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,38928341.0
4,Afghanistan,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,38928341.0
...,...,...,...,...,...,...,...,...,...,...,...,...
14735,Zimbabwe,2021-04-23,365985.0,319732.0,46253.0,14186.0,8755.0,2.46,2.15,0.31,589.0,14862927.0
14736,Zimbabwe,2021-04-24,372099.0,324488.0,47611.0,6114.0,8600.0,2.50,2.18,0.32,579.0,14862927.0
14737,Zimbabwe,2021-04-25,390018.0,336600.0,53418.0,17919.0,10796.0,2.62,2.26,0.36,726.0,14862927.0
14738,Zimbabwe,2021-04-26,411610.0,353834.0,57776.0,21592.0,13517.0,2.77,2.38,0.39,909.0,14862927.0
14739,Zimbabwe,2021-04-27,433939.0,370676.0,63263.0,22329.0,15562.0,2.92,2.49,0.43,1047.0,14862927.0